ssl = no
disable_plaintext_auth = no
mail_location = maildir:/srv/mail/%u
passdb {
  driver = passwd-file
  args = scheme=PLAIN username_format=%u /etc/dovecot/users
}
userdb {
  driver = static
  args = uid=1000 gid=1000 home=/srv/mail/%u
}
namespace inbox {
  inbox = yes
  separator = /
}
service imap-login {
  inet_listener imap {
    port = 143
  }
}
