server_hostname dovecot
server_port 143
listen_address 0.0.0.0
listen_port 143
cache_size 200
cache_expiration_time 1800
enable_select_cache no
foreground_mode true
protocol_log_filename /dev/null
stat_filename /var/run/imapproxy/imapproxy.stat
proc_username nobody
proc_groupname nogroup
connect_retries 2
connect_timeout 10
