server_hostname 127.0.0.1
server_port 9943
listen_address 127.0.0.2
listen_port 1143
cache_size 200
cache_expiration_time 60
enable_select_cache no
force_tls no
connect_retries 2
connect_timeout 10
foreground_mode true
