server_hostname mail.digrepal.com.br
server_port 143
listen_address 127.0.0.2
listen_port 1143
cache_size 200
cache_expiration_time 60
enable_select_cache no
force_tls yes
tls_verify_server yes
connect_retries 2
connect_timeout 10
chroot_directory ""
