foreground = yes
output = /dev/stdout
syslog = no
pid =

[imap-zoho]
client = yes
accept = 127.0.0.1:9993
connect = imap.zoho.com:993
verifyChain = yes
CAfile = /etc/ssl/certs/ca-certificates.crt
checkHost = imap.zoho.com
sslVersionMin = TLSv1.2
