[supervisord]
nodaemon=true
logfile=/var/log/supervisor/supervisord.log
pidfile=/var/run/supervisord.pid

[program:php-fpm]
command=php-fpm -F
autostart=true
autorestart=true
stderr_logfile=/var/log/supervisor/php-fpm.err.log
stdout_logfile=/var/log/supervisor/php-fpm.out.log

[program:nginx]
command=nginx -g "daemon off;"
autostart=true
autorestart=true
stderr_logfile=/var/log/supervisor/nginx.err.log
stdout_logfile=/var/log/supervisor/nginx.out.log

[program:stunnel]
command=stunnel /etc/stunnel/stunnel.conf
autostart=true
autorestart=true
stderr_logfile=/var/log/supervisor/stunnel.err.log
stdout_logfile=/var/log/supervisor/stunnel.out.log

[program:imapproxy-zoho]
command=/usr/local/sbin/in.imapproxyd -f /etc/imapproxy-zoho.conf
autostart=true
autorestart=true
stderr_logfile=/var/log/supervisor/imapproxy-zoho.err.log
stdout_logfile=/var/log/supervisor/imapproxy-zoho.out.log

[program:imapproxy-digrepal]
command=/usr/local/sbin/in.imapproxyd -f /etc/imapproxy-digrepal.conf
autostart=true
autorestart=true
stderr_logfile=/var/log/supervisor/imapproxy-digrepal.err.log
stdout_logfile=/var/log/supervisor/imapproxy-digrepal.out.log
